### ISSUE TITLE
Epsilon tool service for ETL returns a type error 

### ISSUE THREAD

**Issue by barnettwilliam** [epsilonlabs/playground-micronaut#2]
While testing an activity during https://github.com/mdenet/educationplatform/issues/173 the epsilon tool service returned an unexpected error.  The activity that includes a model-to-model transformation to and from the same metamodel effectively copying the input model the following error is returned by the epsilon tool function:

``` 
The value of type 'class org.eclipse.emf.ecore.impl.EEnumLiteralImpl' must be of type 'org.eclipse.emf.ecore.impl.EEnumImpl@424734b4 (name: MoveCommand) (instanceClassName: null) (serializable: true)'
	at (/program.etl@32:1-32:23)
	at (unknown@0:0-0:0)
	at (/program.etl@5:1-5:31)
	at (unknown@0:0-0:0)
	at (/program.etl@1:0-77:1) 
```

The same error was reproducible when running the etl transformation in eclipse when the metamodel ecore file was loaded from the workspace. Registering the metamodel and loading it via its URI from the ePackage registry the same transformation runs successfully without error.

 > Moved from https://github.com/mdenet/platformtools/issues/58

#### Eclipse Version
Eclipse Modeling Tools
Version: 2022-12 (4.26.0)
Build id: 20221201-1913
OS: Linux, v.6.5.0-17-generic, x86_64 / gtk 3.24.33
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.9+9
Java version: 17.0.9

#### Plugin versions  
Epsilon EMF Integration	2.4.0.202203041826	org.eclipse.epsilon.emf.feature.feature.group	Eclipse Modeling Project
  Flexmi	2.4.0.202203041826	org.eclipse.epsilon.flexmi.feature.feature.group	Eclipse Modeling Project
  Flexmi Development Tools	2.4.0.202203041826	org.eclipse.epsilon.flexmi.dt.feature.feature.group	Eclipse Modeling Project
  Human Usable Textual Notation Core	2.4.0.202203041826	org.eclipse.epsilon.hutn.feature.feature.group	Eclipse Modeling Project
  Human Usable Textual Notation Development Tools	2.4.0.202203041826	org.eclipse.epsilon.hutn.dt.feature.feature.group	Eclipse Modeling Project

  EMF - Eclipse Modeling Framework SDK	2.32.0.v20221121-1400	org.eclipse.emf.sdk.feature.group	Eclipse Modeling Project
  Emfatic	1.1.0.202301241109	org.eclipse.emf.emfatic.feature.group	Eclipse.org
  Epsilon EMF Integration	2.4.0.202203041826	org.eclipse.epsilon.emf.feature.feature.group	Eclipse Modeling Project

**Comment by kolovos** [comment]
This is the expected behaviour as, while the metamodels are identical, technically they are two different metamodels. To make this work you'd need to explicitly map enumeration literals as shown in https://eclipse.dev/epsilon/playground/?cb9a688d

**Comment by barnettwilliam** [comment]
Thank you Dimitris we'll fix our example.
